### ISSUE TITLE
nginx returns 502 Bad Gateway after restart

### ISSUE THREAD

**Issue by trevormunoz** [trevormunoz/docker-nginx-es#5]
After using `fig stop` to stop all containers, then `fig start` or `fig up` to restart. nginx returns 502 Bad Gateway errors even though both the proxy and es containers are up (according to `fig ps`)

**Comment by kayiwa** [comment]
This is documented upstream. 

https://github.com/docker/docker/pull/7677

The new container will get a new IP address. (DHCP) Will apply the "Ambassador method" described here or try to think of a way to make this slightly more predictable.

**Comment by trevormunoz** [comment]
Thanks. I will take a look too.

My current use case involves stopping all containers and stopping the host machine—in order to scale down from a higher memory instance to a smaller one.

So I guess I'll need to figure both this and the data-only container pattern

**Comment by trevormunoz** [comment]
~~So I guess I'll need to figure both this and the data-only container pattern~~ &#10003;

For my use case here, I think the data-only container is the better workaround. Better to have a script that exports the index data somewhere easy to copy into a new host rather than worrying about stop/start of the containers to scale an instance down. 

This can probably done with an additional script?

**Comment by kayiwa** [comment]
I am able to fig stop fig up -d with no problem. fig restart seems to lose a container with the branch. See pull request... under separate.

**Comment by trevormunoz** [comment]
Yep. `fig up -d` works fine. However, on the `dumbwaiter` branch that runs the python process again, which I don't want and which stop/start would avoid. 

However, in the end, I don't think I need the python script linked to the other containers (fine to run it separately as a client) so I'l probably just deprecate that branch.
